// Shared types for Story Spark. Keeping these in one place gives the form,
// the API routes, and the reader a single source of truth for the shape of
// a story request and a generated story.

export const AGE_RANGES = ["3-5", "6-8", "9-11"] as const;
export type AgeRange = (typeof AGE_RANGES)[number];

export const STORY_STYLES = [
  "bedtime",
  "funny",
  "adventure",
  "magical",
  "educational",
] as const;
export type StoryStyle = (typeof STORY_STYLES)[number];

export const ILLUSTRATION_STYLES = [
  "soft-watercolor",
  "colorful-picture-book",
  "paper-collage",
  "magical-3d",
] as const;
export type IllustrationStyle = (typeof ILLUSTRATION_STYLES)[number];

export const STORY_LENGTHS = ["short", "standard"] as const;
export type StoryLength = (typeof STORY_LENGTHS)[number];

/** The number of story pages we generate for every book in this prototype. */
export const STORY_PAGE_COUNT = 4;

/** Cover + STORY_PAGE_COUNT pages. Hard ceiling enforced server-side. */
export const MAX_IMAGES_PER_STORY = STORY_PAGE_COUNT + 1;

/** What the browser is allowed to submit. Everything else is decided server-side. */
export interface StoryFormInput {
  idea: string;
  childName?: string;
  ageRange: AgeRange;
  storyStyle: StoryStyle;
  illustrationStyle: IllustrationStyle;
  storyLength: StoryLength;
}

/** One character entry in the model-generated character bible. */
export interface CharacterBibleEntry {
  name: string;
  role: string;
  description: string;
}

/** A single story page as generated by the model (server-side only — includes the illustration prompt). */
export interface GeneratedStoryPage {
  pageNumber: number;
  text: string;
  illustrationPrompt: string;
}

/** The full structured object we ask the model to return. */
export interface GeneratedStory {
  title: string;
  subtitle: string;
  characterBible: CharacterBibleEntry[];
  visualDirection: string;
  coverPrompt: string;
  pages: GeneratedStoryPage[];
}

/** What we keep in the server-side in-memory store for a given story. */
export interface StoryRecord extends GeneratedStory {
  id: string;
  createdAt: number;
  imagesGenerated: number;
  illustrationStyle: IllustrationStyle;
}

/** What the client receives from POST /api/story. No prompts, no character
 *  bible, no visual direction — those stay on the server. */
export interface StoryResponsePage {
  pageNumber: number;
  text: string;
}
export interface StoryResponse {
  storyId: string;
  title: string;
  subtitle: string;
  pages: StoryResponsePage[];
}

/** What the client sends to request an image. */
export type ImageTarget = "cover" | number;
export interface ImageRequestBody {
  storyId: string;
  target: ImageTarget;
}
export interface ImageResponseBody {
  target: ImageTarget;
  image: string; // data: URL
}

export interface ApiErrorResponse {
  error: string;
}
